### ISSUE TITLE
Cannot read property 'split' of null

### ISSUE THREAD

**Issue by isc-rsingh** [ibm-cds-labs/couchdb-db-transform#2]
``` bash
rrsinghcbookpro: export SOURCE_COUCH_DB_URL=http://localhost:5984/crimes
rrsinghcbookpro: export TARGET_COUCH_DB_URL=http://localhost:5984/cchi
rrsinghcbookpro: export TRANSFORM_FUNCTION=no.js
rrsinghcbookpro: node app.js

/Users/rajrsingh/workspace/couchdb-db-transform/lib/util.js:73
            urlObj.auth = urlObj.auth.split(':')[0];
                                     ^

TypeError: Cannot read property 'split' of null
    at Object.getUrlWithoutPassword (/Users/rajrsingh/workspace/couchdb-db-transform/lib/util.js:73:28)
    at new CloudantRepository (/Users/rajrsingh/workspace/couchdb-db-transform/lib/util/cloudantRepository.js:55:35)
    at Replicator.<anonymous> (/Users/rajrsingh/workspace/couchdb-db-transform/lib/replicate.js:112:13)
    at Request._callback (/Users/rajrsingh/workspace/couchdb-db-transform/node_modules/nano/lib/nano.js:217:16)
    at Request.self.callback (/Users/rajrsingh/workspace/couchdb-db-transform/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/rajrsingh/workspace/couchdb-db-transform/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
```

**Comment by ptitzler** [comment]
Yup, sorry. My tests were all run against a hosted CouchDB, hence this one slipped through. I will add logic to cover the scenario where the URL does not contain credentials.

**Comment by ptitzler** [comment]
Delivered by #3
